### ISSUE TITLE
Error in log, after first adjustments, but no crash.

### ISSUE THREAD

**Issue by tshirtman** [kootenpv/brightml#2]
```
Change your brightness to create your first data sample (there is no data found).
Task exception was never retrieved
future: <Task finished coro=<Brightml.retrain() done, defined at /home/gabriel/.local/lib/python3.5/site-packages/brightml/brightml.py:53> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/gabriel/.local/lib/python3.5/site-packages/brightml/brightml.py", line 55, in retrain
    features = get_features()
  File "/home/gabriel/.local/lib/python3.5/site-packages/brightml/features.py", line 46, in get_features
    data.update(d.last_value)
TypeError: 'NoneType' object is not iterable
RETRAINING
```

**Comment by kootenpv** [comment]
I cannot reproduce. After deleting ~/.brightml it still works for me. Changing brightness and changing window in any order works for me without errors.

Could you delete ~/.brightml and restart `sudo brightml` and let me know if it still works?
Otherwise, maybe a short description of how I could mimic your situation.

Thanks so much for taking the time to post the issues! I hope it will work soon :-)

**Comment by tshirtman** [comment]
trying, seems i didln't have the error this time (after deleting/restarting) will keep you updated.

(oh, and now it indeed seem to have more effect! i was wondering how much training time was necessary, but it seems it wasn't training properly)

also, no problem, i may dive in the code in the future if i see things to add. Thank you for sharing!

**Comment by kootenpv** [comment]
Awesome! Please let me know if you find it usable on a day to day basis!
